controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

# nelmio_cors:
#     resource: "@NelmioCorsBundle/Resources/config/routes.yaml"
#     prefix: /api